services:
  - type: web
    name: pt-dr-ray-backend
    runtime: python
    rootDir: ./backend
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
    plan: free

  - type: web
    name: pt-dr-ray-frontend
    runtime: node
    rootDir: ./frontend
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://pt-dr-ray-backend.onrender.com
    plan: free